server:
  port: 8081

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: minicampus_user
    password: a1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: chappse6@gmail.com
    password: itjrrbercwnmzwkr
    properties:
      mail:
        smtp:
          starttls:
            enable: true



